### ISSUE TITLE
HTTP 500 Error for https://browscap.org/stream?q=BrowsCapINI

### ISSUE THREAD

**Issue by madhancock** [browscap/browscap-site#444]
**Describe the bug**
Browscap configuration URL is returning a HTTP 500 error as of last night. Affects all configuration versions.

**To Reproduce**
1. Go to https://browscap.org/stream?q=BrowsCapINI
2. See error.

**Expected behavior**
Configuration response.

**Comment by asgrim** [comment]
Thanks for reporting this. It this seems to be because we've hit our `max_questions` limit in our database. 

Checking our Cloudflare logs, it looks like we've had an enormous increase in number of requests over the last 24 hours (since around 3pm yesterday afternoon), which probably explains that.

I have enabled "under attack" mode, perhaps that will reduce the traffic for a while.

**Comment by asgrim** [comment]
Maintenance mode is now disabled; the 500 errors are gone, I will continue monitoring, but leaving "under attack" mode on (so automated processes may struggle with this)

**Comment by alexandru-mohora-rm** [comment]
> Maintenance mode is now disabled; the 500 errors are gone, I will continue monitoring, but leaving "under attack" mode on (so automated processes may struggle with this)
I can confirm that the automated processes are still blocked by CF's "under attack" mode.

**Comment by asgrim** [comment]
> Are you planning to switch off "under attack" mode?

Yes. I am monitoring traffic, and am gradually reducing the levels on Cloudflare over time.

**Comment by asgrim** [comment]
Traffic should be back to normal now. I'm no longer seeing a traffic spike. Thanks for the report @madhancock - please do let me know if there are still any issues.
