### ISSUE TITLE
Automatic updates of browscap

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-site#48]
We should automate this: https://github.com/browscap/browscap/wiki/Public-release-procedure

The process could probably be a script or something I can run periodically. The process is basically:

## browscap/browscap
 - determine github milestone ID (e.g. 1.0.0 = 11)
 - make a new milestone for 1.0.1
 - move any remaining 1.0.0 tickets to 1.0.1
 - run `changelog_generator.php -c ~/path_to_config.php -u browscap -r browscap -m 56` for notes
 - close milestone 1.0.0
 - git pull
 - git tag -s 1.0.0
 - message = changelog
 - git push origin 1.0.0
 - create github release for version

## browscap/browscap-site
 - docker-compose run php-server composer require browscap/browscap 6.0.33
 - git commit -m "Update site to serve browscap 6.0.33"
 - git push

**Comment by jaydiablo** [comment]
For the browscap/browscap-site piece, would be nice if it was something that could be triggered by the release of browscap/browscap, perhaps something running on AWS Lambda + API Gateway or similar so a server isn't necessary to maintain. I assume it's possible to install hooks or something so that Github can make a call somewhere when a release is cut.

That could probably be done in Travis too, but I don't think travis builds are done when a release is made, and we wouldn't want it updating the browscap.org site on every merge to master.

**Comment by asgrim** [comment]
Yup sounds like sorta thing I want to do

**Comment by mimmi20** [comment]
Is there a Github Action for this?

**Comment by asgrim** [comment]
I'm hoping #63 will fix the site part of this process!
